/**
 * Translation keys for Advocate Registration Module
 * These keys should be registered in the localization service
 * Format: MODULE_KEY_NAME
 */

export const AdvocateRegistrationTranslations = {
  // Module Name
  ADVOCATE_REGISTRATION: "ADVOCATE_REGISTRATION",
  ADVOCATE_REGISTRATION_DESC: "ADVOCATE_REGISTRATION_DESC",
  
  // Sign In Page
  SIGN_IN_TO_YOUR_ACCOUNT: "SIGN_IN_TO_YOUR_ACCOUNT",
  WELCOME_BACK_ENTER_CREDENTIALS: "WELCOME_BACK_ENTER_CREDENTIALS",
  SIGN_IN: "SIGN_IN",
  
  // Role Selection
  JUDGE_COURT_STAFF: "JUDGE_COURT_STAFF",
  ADVOCATE_LITIGANT: "ADVOCATE_LITIGANT",
  
  // Form Fields
  PHONE_NO: "PHONE_NO",
  ENTER_MOBILE_NUMBER: "ENTER_MOBILE_NUMBER",
  
  // Registration
  DONT_HAVE_ACCOUNT: "DONT_HAVE_ACCOUNT",
  REGISTER_HERE: "REGISTER_HERE",
  ADVOCATE_REGISTER: "ADVOCATE_REGISTER",
  ADVOCATE_REGISTRATION_FORM: "ADVOCATE_REGISTRATION_FORM",
  
  // Register Page
  TELL_US_ABOUT_YOURSELF: "TELL_US_ABOUT_YOURSELF",
  REGISTER_SUBTITLE: "REGISTER_SUBTITLE",
  IM_A_LITIGANT: "IM_A_LITIGANT",
  LITIGANT_DESCRIPTION: "LITIGANT_DESCRIPTION",
  IM_AN_ADVOCATE: "IM_AN_ADVOCATE",
  ADVOCATE_DESCRIPTION: "ADVOCATE_DESCRIPTION",
  IM_AN_ADVOCATES_CLERK: "IM_AN_ADVOCATES_CLERK",
  CLERK_DESCRIPTION: "CLERK_DESCRIPTION",
  CONTINUE: "CONTINUE",
  
  // Mobile Number Entry Page (module-specific keys to avoid override by core/backend)
  PLEASE_ENTER_YOUR_MOBILE_NUMBER: "PLEASE_ENTER_YOUR_MOBILE_NUMBER",
  MOBILE_NUMBER_SUBTITLE: "MOBILE_NUMBER_SUBTITLE",
  DIGIT_ASSIGNMENT_PLEASE_ENTER_YOUR_MOBILE_NUMBER: "DIGIT_ASSIGNMENT_PLEASE_ENTER_YOUR_MOBILE_NUMBER",
  DIGIT_ASSIGNMENT_MOBILE_NUMBER_SUBTITLE: "DIGIT_ASSIGNMENT_MOBILE_NUMBER_SUBTITLE",
  MOBILE_NO: "MOBILE_NO",
  VERIFY_YOUR_MOBILE_NUMBER: "VERIFY_YOUR_MOBILE_NUMBER",
  OTP_INSTRUCTION: "OTP_INSTRUCTION",
  REQUEST_NEW_OTP_IN: "Request a new OTP in",
  RESEND_OTP: "RESEND_OTP",
  VERIFY: "VERIFY",
  CS_INVALID_OTP: "CS_INVALID_OTP",
  CS_COMMON_CLOSE: "CS_COMMON_CLOSE",

  // Advocate Verification Page
  ADVOCATE_VERIFICATION: "ADVOCATE_VERIFICATION",
  ADVOCATE_VERIFICATION_SUBTITLE: "ADVOCATE_VERIFICATION_SUBTITLE",
  STATE_OF_REGISTRATION: "STATE_OF_REGISTRATION",
  SELECT_STATE: "SELECT_STATE",
  BAR_REGISTRATION_NUMBER: "BAR_REGISTRATION_NUMBER",
  ENTER_BAR_REGISTRATION_NUMBER: "ENTER_BAR_REGISTRATION_NUMBER",
  UPLOAD_BAR_COUNCIL_ID: "UPLOAD_BAR_COUNCIL_ID",
  NO_FILES_UPLOADED: "NO_FILES_UPLOADED",
  ONE_FILE_UPLOADED: "ONE_FILE_UPLOADED",
  PLEASE_UPLOAD_BAR_COUNCIL_ID: "PLEASE_UPLOAD_BAR_COUNCIL_ID",
  REQUIRED_FIELD: "REQUIRED_FIELD",
  ERR_FILE_SIZE_EXCEEDED: "ERR_FILE_SIZE_EXCEEDED",
  PREVIEW_IMAGE: "PREVIEW_IMAGE",
  REMOVE_IMAGE: "REMOVE_IMAGE",
  CS_COMMON_CHOOSE_FILE: "CS_COMMON_CHOOSE_FILE",

  // Application Status
  ADVOCATE_APPLICATION_STATUS: "ADVOCATE_APPLICATION_STATUS",
  ADVOCATE_APPLICATION_DETAILS: "ADVOCATE_APPLICATION_DETAILS",
  
  // Footer Links
  WANT_TO_KNOW_MORE: "WANT_TO_KNOW_MORE",
  VIEW_OUR_SOP: "VIEW_OUR_SOP",
  WATCH_PLATFORM_VIDEO: "WATCH_PLATFORM_VIDEO",
  OR: "OR",
  
  // Errors
  ERR_INVALID_MOBILE_NUMBER: "ERR_INVALID_MOBILE_NUMBER",

  // Name Entry
  ENTER_YOUR_NAME_OFFICIAL: "ENTER_YOUR_NAME_OFFICIAL",
  NAME_ENTRY_SUBTITLE: "NAME_ENTRY_SUBTITLE",
  FIRST_NAME: "FIRST_NAME",
  MIDDLE_NAME: "MIDDLE_NAME",
  OPTIONAL: "OPTIONAL",
  ENTER_FIRST_NAME: "ENTER_FIRST_NAME",
  ENTER_MIDDLE_NAME: "ENTER_MIDDLE_NAME",
  ENTER_LAST_NAME: "ENTER_LAST_NAME",
  LAST_NAME: "LAST_NAME",
  ERR_NAME_REQUIRED: "ERR_NAME_REQUIRED",

  // Address Entry
  ENTER_YOUR_ADDRESS: "ENTER_YOUR_ADDRESS",
  SEARCH_BUILDING_STREET_AREA: "SEARCH_BUILDING_STREET_AREA",
  MOVE_PIN_INSTRUCTION: "MOVE_PIN_INSTRUCTION",
  MOVE_PIN_TO_EXACT_LOCATION: "MOVE_PIN_TO_EXACT_LOCATION",
  PINCODE: "PINCODE",
  ENTER_PINCODE: "ENTER_PINCODE",
  STATE: "STATE",
  DISTRICT: "DISTRICT",
  CITY_TOWN: "CITY_TOWN",
  CORE_COMMON_PINCODE: "CORE_COMMON_PINCODE",
  CORE_COMMON_STATE: "CORE_COMMON_STATE",
  CORE_COMMON_DISTRICT: "CORE_COMMON_DISTRICT",
  CORE_COMMON_CITY_OR_TOWN: "CORE_COMMON_CITY_OR_TOWN",
  LOCALITY_STREET_AREA: "LOCALITY_STREET_AREA",
  LOCALITY_STREET_NAME_AREA: "LOCALITY_STREET_NAME_AREA",
  ENTER_LOCALITY_STREET_AREA: "ENTER_LOCALITY_STREET_AREA",
  DOOR_NUMBER: "DOOR_NUMBER",
  ENTER_DOOR_NUMBER: "ENTER_DOOR_NUMBER",
  ERR_ADDRESS_REQUIRED: "ERR_ADDRESS_REQUIRED",
  ERR_INVALID_PINCODE: "ERR_INVALID_PINCODE",
  SELECT_STATE: "SELECT_STATE",

  // Verify Identity
  VERIFY_YOUR_IDENTITY: "VERIFY_YOUR_IDENTITY",
  VERIFY_IDENTITY_SUBTITLE: "VERIFY_IDENTITY_SUBTITLE",
  AADHAAR_RECOMMENDED: "AADHAAR_RECOMMENDED",
  AADHAAR_DESCRIPTION: "AADHAAR_DESCRIPTION",
  OTHER_ID: "OTHER_ID",
  OTHER_ID_DESCRIPTION: "OTHER_ID_DESCRIPTION",

  // Aadhaar Entry
  ENTER_YOUR_AADHAAR_NUMBER: "ENTER_YOUR_AADHAAR_NUMBER",
  AADHAAR_12_DIGIT_INSTRUCTION: "AADHAAR_12_DIGIT_INSTRUCTION",
  GET_OTP: "GET_OTP",
  ERR_INVALID_AADHAAR: "ERR_INVALID_AADHAAR",
  VERIFY_YOUR_AADHAAR: "VERIFY_YOUR_AADHAAR",
  AADHAAR_OTP_INSTRUCTION: "AADHAAR_OTP_INSTRUCTION",

  // Terms and Conditions
  TERMS_AND_CONDITIONS: "TERMS_AND_CONDITIONS",
  TNC_INTRO: "TNC_INTRO",
  I_ACCEPT_TERMS: "I_ACCEPT_TERMS",
  PROCEED: "PROCEED",

  // Application Status (waiting approval)
  REGISTRATION_APPROVED: "REGISTRATION_APPROVED",
  REGISTRATION_REJECTED: "REGISTRATION_REJECTED",
  REGISTRATION_WAITING_APPROVAL: "REGISTRATION_WAITING_APPROVAL",
  REGISTRATION_IN_PROGRESS: "REGISTRATION_IN_PROGRESS",
  IS_IN_PROGRESS: "IS_IN_PROGRESS",
  VERIFICATION_DAYS_AND_SMS: "VERIFICATION_DAYS_AND_SMS",
  VIEW_MY_APPLICATION: "VIEW_MY_APPLICATION",

  // Registered Successfully
  REGISTERED_SUCCESSFULLY: "REGISTERED_SUCCESSFULLY",
  CAN_NOW_FILE_OR_JOIN_CASE: "CAN_NOW_FILE_OR_JOIN_CASE",
  FILE_A_CASE: "FILE_A_CASE",
  JOIN_A_CASE: "JOIN_A_CASE",

  // My Application (view application)
  MY_APPLICATION: "MY_APPLICATION",
  MOBILE_NUMBER: "MOBILE_NUMBER",
  ID_TYPE: "ID_TYPE",
  AADHAR_NUMBER: "AADHAR_NUMBER",
  NAME: "NAME",
  LOCATION: "LOCATION",
  VIEW_ON_MAP: "VIEW_ON_MAP",
  ADDRESS: "ADDRESS",
  BAR_REGISTRATION_NO: "BAR_REGISTRATION_NO",
  BAR_COUNCIL_ID: "BAR_COUNCIL_ID",
  TAKE_ME_HOME: "TAKE_ME_HOME",

  // Other ID placeholder
  OTHER_ID_VERIFICATION: "OTHER_ID_VERIFICATION",
  OTHER_ID_COMING_SOON: "OTHER_ID_COMING_SOON",
};
